### ISSUE TITLE
System didn't recognize the signature of driver

### ISSUE THREAD

**Issue by charleszhao999** [DirkoAudio/ASIOLinkProFIX#2]
If I install the ASIOLinkPro alone, the driver runs well.
But after I patched it, the system warns that the driver can't be verified because of the signature. And after a reboot, all vitual audio devices disappeared.
![QQ截图20230104205315](https://user-images.githubusercontent.com/63227229/210559534-17a2925b-f17c-41d1-88dc-9b51bc848f92.png)

I've tried to reboot to disable the driver signature enforcement, and everything worked properly, but once if I restart again, the problem appears again.

**Comment by charleszhao999** [comment]
Translated message in the screenshot:
"Windows cannot verify the digital signature for the drivers required for this device. A recent software or hardware change might have installed a file with a signed incorrectly or damaged file, or the installation of a file from an unknown source might be blocked to help protect your computer." (code 52)

**Comment by HotshotGT** [comment]
I'm having the same problem as well:
![image](https://github.com/DirkoAudio/ASIOLinkProFIX/assets/38869741/bd014e48-15cf-4966-bf4a-fb462569fb14)

I haven't tried disabling Windows driver signature enforcement myself, but I suppose that could be a temporary workaround if you don't mind the security implications: https://www.thewindowsclub.com/disable-driver-signature-enforcement-windows

**Comment by DirkoAudio** [comment]
Add this registry to your logon/logout scripts OR startup folder OR scheduled task ...or whatever method you prefer - you need to make sure this entry is always there.

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\CI\Policy]
"UpgradedSystem"=dword:00000001

After using the first time, a reboot is necessary and, in the next boot, you need to make sure the entry is always there.
If everything is fine, you should see the driver for use, even with Secure Boot enabled in BIOS.

The other workaround is to disable secure boot in bios.

**Comment by HotshotGT** [comment]
> Add this registry to your logon/logout scripts OR startup folder OR scheduled task ...or whatever method you prefer - you need to make sure this entry is always there.
> 
> [HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\CI\Policy] "UpgradedSystem"=dword:00000001
> 
> After using the first time, a reboot is necessary and, in the next boot, you need to make sure the entry is always there. If everything is fine, you should see the driver for use, even with Secure Boot enabled in BIOS.
> 
> The other workaround is to disable secure boot in bios.

Awesome, thanks. I initially got it working by turning off secure boot, but this is a much nicer option.

**Comment by JetErorr** [comment]
This worked for me too, no more Discord sound bite cuts. 

I created a .cmd file with the following: 
`REG ADD HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\CI\Policy /v UpgradedSystem /t REG_DWORD /d 00000001 /f`

and created a task in Task Scheduler to execute this file on user logon (with 'Run with highest privileges' checked).
